### ISSUE TITLE
Can't Create PDF

### ISSUE THREAD

**Issue by joelcdoyle** [jnutter/phantom-pdf#2] opened 2015-04-08 20:29 UTC
I get this error when I try to create a PDF. Any idea what it means?

```
15:26:36 web.1   | Phantom booted
15:26:36 web.1   | Reading config files
15:26:36 web.1   |
15:26:36 web.1   | Removing config files
15:26:36 web.1   | Loading page
15:26:36 web.1   |
15:26:36 web.1   | Booting page in phantom
15:26:36 web.1   |
15:26:36 web.1   | Register handlebar helpers
15:26:36 web.1   |
15:26:36 web.1   | PHANTOM ERROR: TypeError: 'undefined' is not an object (evaluating 'request[0]')
```

**Comment by sheltowt** [comment] 2015-05-18 18:01
any luck on this?  I am receiving the same error?

**Comment by kuskov** [comment] 2015-06-26 21:45
The problem is that the author doesn't validate the manifest and if you remove single value from manifest, it doesn't work anymore. I had the same problem when i removed:
helpers: __dirname+'/helpers/index.js',

**Comment by jnutter** [comment] 2015-09-21 18:47
Thanks @ekussberg for answering! Will get some fixes for this.

**Comment by gcmeen** [comment] 2016-12-14 12:05
ReferenceError: Can't find variable: process

.....newapp/node_modules/path/path.js:25
.....newapp/node_modules/path/path.js:629

Phantom booted

Reading config files

Removing config files
Loading page

Booting page in phantom

Set headers and footers

Setup page

Register parcials
Register CSS parcials
Setting content
Content set
Page finished loading success


don't get any error while running but not generated pdf.. can somebody help me to fix this????
 @ekussberg

**Comment by jnutter** [comment] 2016-12-14 18:03
Addressed in https://github.com/jnutter/phantom-pdf/issues/17

**Closed by jnutter** 2016-12-14 18:03 UTC
