### ISSUE TITLE
error: 'PhantomJS not installed'

### ISSUE THREAD

**Issue by gcmeen** [jnutter/phantom-pdf#15] opened 2016-10-05 11:52 UTC
got error: 'PhantomJS not installed' but i have install it.
help me to fix it. here is code:

var manifest = {
        templates: {
            body:'./lib/body.hbs',
            footer :'./lib/footer.hbs',
        },
        helpers: './lib/helper.js', // Handlebars helper
        helperVariables: {}, // Additional data to be passed in the helper such as local
        output: filename, // This is the destination of the newly created PDF
        tmpDir: './temp',
        phantomSettings: {
            paperSize: {
                format: 'A4',
                orientation: 'portrait',
                margin: {
                    top: '0.25in',
                    right: '0.5in',
                    bottom: '0.25in',
                    left: '0.5in'
                },
                header: {
                    height: '0.5in'
                },
                footer: {
                    height: '0.5in'
                }
            }
        }
    };
    var pdf = new PhantomPDF(manifest, data, function (err) {
        if (err) {
           debug('error  : ',err);
        }
    });

**Comment by jnutter** [comment] 2016-12-14 18:01
Duplicate of https://github.com/jnutter/phantom-pdf/issues/16

**Closed as completed by jnutter** 2016-12-14 18:01 UTC
